version: '2'
services: 
  web:
    build: ./
    image: linebot-web
    ports: 
      - "3000:3000"
    volumes: 
      - "./web:/usr/local/linebot"
    container_name: linebot-web
    environment: 
      - CHANNEL_SECRET=<SECRET>
      - CHANNEL_ACCESS_TOKEN=<TOKEN>